ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: octane.codeware.icu
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - octane.codeware.icu
    secretName: letsencrypt-production
